[system]
compatible=co-pilot-${MACHINE}
bootloader=uboot
mountprefix=/run/rauc
data-directory=/data/rauc

[keyring]
path=/etc/rauc/ca.cert.pem
use-bundle-signing-time=true

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs_a
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs_b
type=ext4
bootname=B

[slot.boot.0]
device=/dev/disk/by-partlabel/boot
type=raw
