#!/usr/bin/env bash
# Bump sigma recipe SRCREVs to each repo's pushed main HEAD, then refresh the
# autogenerated crates.inc files via cargo-update-recipe-crates.
#
# Usage:
#   scripts/bump-recipe-revs.sh            # rewrite SRCREVs, then update crates
#   scripts/bump-recipe-revs.sh --check    # report stale pins, change nothing
#
# The crates step needs a sourced BitBake environment (setup-environment.sh);
# without one the script prints the commands to run instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WINGMAN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RECIPES_ROOT="${WINGMAN_ROOT}/meta-sigma-racer-wingman/recipes-sigma-racer-wingman"

# recipe name | .bb path (relative to RECIPES_ROOT) | source repo
PINS=(
  "sigma-racer-vehicle|sigma-racer-vehicle/sigma-racer-vehicle.bb|sigma-racer-vehicle"
  "sigma-telemetry-relay|diagnostics-service/sigma-telemetry-relay.bb|sigma-racer-telemetry"
  "sigma-racer-cluster|sigma-racer-cluster/sigma-racer-cluster_git.bb|sigma-racer-cluster"
)

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

remote_head() {
  local repo="$1"
  git ls-remote "https://github.com/sigmatactical-org/${repo}.git" refs/heads/main \
    | cut -f1
}

stale=0
touched=()
for pin in "${PINS[@]}"; do
  IFS='|' read -r recipe bb repo <<<"${pin}"
  bb_path="${RECIPES_ROOT}/${bb}"

  current="$(sed -n 's/^SRCREV = "\([0-9a-f]\{40\}\)"/\1/p' "${bb_path}")"
  if [[ -z "${current}" ]]; then
    echo "error: no full-SHA SRCREV found in ${bb}" >&2
    exit 1
  fi

  latest="$(remote_head "${repo}")"
  if [[ -z "${latest}" ]]; then
    echo "error: could not resolve main HEAD of ${repo}" >&2
    exit 1
  fi

  if [[ "${current}" == "${latest}" ]]; then
    echo "ok    ${recipe} (${current:0:7})"
    continue
  fi

  stale=1
  if [[ "${CHECK_ONLY}" == "1" ]]; then
    echo "stale ${recipe}: ${current:0:7} -> ${latest:0:7}"
  else
    sed -i "s/^SRCREV = \"${current}\"/SRCREV = \"${latest}\"/" "${bb_path}"
    echo "bump  ${recipe}: ${current:0:7} -> ${latest:0:7}"
    touched+=("${recipe}")
  fi
done

if [[ "${CHECK_ONLY}" == "1" ]]; then
  exit "${stale}"
fi

if [[ "${#touched[@]}" -eq 0 ]]; then
  echo "All pins current — nothing to do."
  exit 0
fi

# Refresh the autogenerated crates.inc for every bumped recipe. The lockfile
# a recipe vendors from may have changed even when its own SRCREV did not
# (path-dep siblings), so update all of them when anything moved.
if command -v bitbake >/dev/null 2>&1; then
  for pin in "${PINS[@]}"; do
    IFS='|' read -r recipe _ _ <<<"${pin}"
    echo "update_crates ${recipe} ..."
    bitbake -c update_crates "${recipe}"
  done
else
  cat <<EOF

SRCREVs updated. To refresh the crates.inc files, source the build
environment and run:

  . ./setup-environment.sh
$(for pin in "${PINS[@]}"; do IFS='|' read -r recipe _ _ <<<"${pin}"; echo "  bitbake -c update_crates ${recipe}"; done)
EOF
fi
